//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.03 at 09:53:05 PM CEST 
//


package com.example.springapp.types;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.springapp.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.springapp.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateMovieRequest }
     * 
     */
    public CreateMovieRequest createCreateMovieRequest() {
        return new CreateMovieRequest();
    }

    /**
     * Create an instance of {@link CreateDirectorRequest }
     * 
     */
    public CreateDirectorRequest createCreateDirectorRequest() {
        return new CreateDirectorRequest();
    }

    /**
     * Create an instance of {@link CreateDirectorResponse }
     * 
     */
    public CreateDirectorResponse createCreateDirectorResponse() {
        return new CreateDirectorResponse();
    }

    /**
     * Create an instance of {@link BaseResponse }
     * 
     */
    public BaseResponse createBaseResponse() {
        return new BaseResponse();
    }

    /**
     * Create an instance of {@link CreateMovieResponse }
     * 
     */
    public CreateMovieResponse createCreateMovieResponse() {
        return new CreateMovieResponse();
    }

}
