//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.22 at 08:36:27 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://types.springapp.example.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.springapp.types;
